services:
  meilisearch:
    image: getmeili/meilisearch:v1.15@sha256:fe500cf9cca05cb9f027981583f28eccf17d35d94499c1f8b7b844e7418152fc
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    logging:
      driver: loki
      options:
        mode: non-blocking
        loki-url: ${LOKI_URL}
        loki-batch-size: "10"
        loki-timeout: "10s"
        loki-retries: "3"
    secrets:
      - MEILI_MASTER_KEY
    volumes:
      - ./meili_data:/meili_data
    networks:
      - main_net
    command: sh -c "meilisearch --master-key $$(cat /run/secrets/MEILI_MASTER_KEY)"

  redis:
    image: redis:8.0.2-alpine@sha256:48501c5ad00d5563bc30c075c7bcef41d7d98de3e9a1e6c752068c66f0a8463b
    networks:
      - main_net
    volumes:
      - ./redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    logging:
      driver: loki
      options:
        mode: non-blocking
        loki-url: ${LOKI_URL}
        loki-batch-size: "10"
        loki-timeout: "10s"
        loki-retries: "3"

  scylladb:
    image: scylladb/scylla:2025.1.2@sha256:84e914792c61a7703ff616bf6ee6d4becbcf68845221bd2458fcab10ef64302c
    networks:
      - main_net
    volumes:
      - ./scylladb_data:/var/lib/scylla
    command: --smp=1 --memory=1G --overprovisioned=1 --api-address=0.0.0.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    logging:
      driver: loki
      options:
        mode: non-blocking
        loki-url: ${LOKI_URL}
        loki-batch-size: "10"
        loki-timeout: "10s"
        loki-retries: "3"

  rust:
    image: main_rust:latest
    networks:
      - main_net
    volumes:
      - ${RUST_DEVICE_FOLDER_PATH}:${RUST_CONTAINER_FOLDER_PATH}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    secrets:
      # Bot
      - RUST_BOT_CUTS_KEY
      # Swap
      - RUST_FROM_EMAIL
      - RUST_FROM_EMAIL_PASSWORD
      - RUST_FROM_EMAIL_SERVER
      - SWAP_API_TOKEN
      # Other
      - HOUSING_API_TOKEN
      - HOME_API_TOKEN
      - MEILI_ADMIN_KEY
    logging:
      driver: loki
      options:
        mode: non-blocking
        loki-url: ${LOKI_URL}
        loki-batch-size: "10"
        loki-timeout: "10s"
        loki-retries: "3"
    environment:
      # Server
      - RUST_PORT=${RUST_PORT}
      - RUST_LOG=${RUST_LOG}
      - RUST_DB_URI=${RUST_DB_URI}
      - RUST_REDIS_URL=${RUST_REDIS_URL}
      - SVELTE_URL=${SVELTE_URL}
      - MEILI_URL=${MEILI_URL}
      - RUST_CONTAINER_FOLDER_PATH=${RUST_CONTAINER_FOLDER_PATH}
      # Housing
      - RUST_HOUSING_FILE=${RUST_HOUSING_FILE}
      - PUBLIC_HOUSING_MAX_CHARS=${PUBLIC_HOUSING_MAX_CHARS}
      - PUBLIC_HOUSING_MIN_CHARS=${PUBLIC_HOUSING_MIN_CHARS}
      # Swap
      - RUST_MAX_SESSIONS=${RUST_MAX_SESSIONS}
      - RUST_AUTH_MAX_ATTEMPTS=${RUST_AUTH_MAX_ATTEMPTS}
      - RUST_AUTH_LOCK_DURATION_SECS=${RUST_AUTH_LOCK_DURATION_SECS}
      - RUST_VERIFY_MAX_ATTEMPTS=${RUST_VERIFY_MAX_ATTEMPTS}
      - RUST_VERIFY_LOCK_DURATION_SECS=${RUST_VERIFY_LOCK_DURATION_SECS}
      - RUST_MAX_CODES=${RUST_MAX_CODES}
      - RUST_MAX_CODES_DURATION_SECS=${RUST_MAX_CODES_DURATION_SECS}
      - RUST_MAX_ITEMS=${RUST_MAX_ITEMS}
      - PUBLIC_TEMP_SESSION_DURATION_SECS=${PUBLIC_TEMP_SESSION_DURATION_SECS}
      - RUST_SESSION_DURATION_SECS=${RUST_SESSION_DURATION_SECS}
      - PUBLIC_MAX_CHARS=${PUBLIC_MAX_CHARS}
      - PUBLIC_CODE_LENGTH=${PUBLIC_CODE_LENGTH}
      - PUBLIC_MIN_PASSWORD_LENGTH=${PUBLIC_MIN_PASSWORD_LENGTH}
      # Bot
      - RUST_BOT_NUM_PICTURES=${RUST_BOT_NUM_PICTURES}
      - RUST_BOT_PICTURES_TTL=${RUST_BOT_PICTURES_TTL}
      - RUST_BOT_MAX_BYTES=${RUST_BOT_MAX_BYTES}
      - RUST_BOT_PHOTO_URL=${RUST_BOT_PHOTO_URL}
      - RUST_BOT_BACKGROUND_CONTAINER_FOLDER_PATH=${RUST_BOT_BACKGROUND_CONTAINER_FOLDER_PATH}
      - RUST_BOT_BACKGROUND_FILE=${RUST_BOT_BACKGROUND_FILE}
      - RUST_BOT_PETE_FILE=${RUST_BOT_PETE_FILE}
      - RUST_BOT_TOWER_FILE=${RUST_BOT_TOWER_FILE}
      - RUST_BOT_FOUNTAIN_FILE=${RUST_BOT_FOUNTAIN_FILE}

  svelte:
    image: main_svelte:latest
    networks:
      - main_net
    secrets:
      - SWAP_API_TOKEN
      - HOUSING_API_TOKEN
      - HOME_API_TOKEN
      - SEARCH_TOKEN
    command: sh -c "export HOUSING_API_TOKEN=$$(cat /run/secrets/HOUSING_API_TOKEN) && export HOME_API_TOKEN=$$(cat /run/secrets/HOME_API_TOKEN) && export SWAP_API_TOKEN=$$(cat /run/secrets/SWAP_API_TOKEN) && export SEARCH_TOKEN=$$(cat /run/secrets/SEARCH_TOKEN) && node build"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${SVELTE_PORT}
      - PUBLIC_MEILI_KEY=${PUBLIC_MEILI_KEY}

  caddy:
    image: main_caddy:latest
    networks:
      - main_net
    secrets:
      - SWAP_API_TOKEN
      - HOUSING_API_TOKEN
      - HOME_API_TOKEN
      - SEARCH_TOKEN
    ports:
      - "80:80"
      - "443:443"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    logging:
      driver: loki
      options:
        mode: non-blocking
        loki-url: ${LOKI_URL}
        loki-batch-size: "10"
        loki-timeout: "10s"
        loki-retries: "3"
    command: sh -c "export HOUSING_API_TOKEN=$$(cat /run/secrets/HOUSING_API_TOKEN) && export HOME_API_TOKEN=$$(cat /run/secrets/HOME_API_TOKEN) && export SWAP_API_TOKEN=$$(cat /run/secrets/SWAP_API_TOKEN) && export SEARCH_TOKEN=$$(cat /run/secrets/SEARCH_TOKEN) && caddy run --config /etc/caddy/Caddyfile"
    environment:
      - CADDY_LOG_ROTATE_DAYS=356
      - CADDY_LOG_ROTATE_SIZE=10000
      - CADDY_DOMAIN=${CADDY_DOMAIN}
      - RUST_NAME=${RUST_NAME}
      - RUST_PORT=${RUST_PORT}
      - SVELTE_NAME=${SVELTE_NAME}
      - SVELTE_PORT=${SVELTE_PORT}
      - MEILI_NAME=${MEILI_NAME}
      - PUBLIC_MEILI_PATH=${PUBLIC_MEILI_PATH}
      - MEILI_PORT=${MEILI_PORT}
      - PUBLIC_SWAP_BACKEND_PATH=${PUBLIC_SWAP_BACKEND_PATH}
      - PUBLIC_HOUSING_BACKEND_PATH=${PUBLIC_HOUSING_BACKEND_PATH}
      - PUBLIC_HOME_BACKEND_PATH=${PUBLIC_HOME_BACKEND_PATH}
    volumes:
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/logs:/var/log/caddy
      - ./caddy/config/Caddyfile:/etc/caddy/Caddyfile

secrets:
  RUST_BOT_CUTS_KEY:
    external: true
  RUST_FROM_EMAIL:
    external: true
  RUST_FROM_EMAIL_PASSWORD:
    external: true
  RUST_FROM_EMAIL_SERVER:
    external: true
  SWAP_API_TOKEN:
    external: true
  HOUSING_API_TOKEN:
    external: true
  HOME_API_TOKEN:
    external: true
  MEILI_MASTER_KEY:
    external: true
  SEARCH_TOKEN:
    external: true
  MEILI_ADMIN_KEY:
    external: true

networks:
  main_net:
    external: true
    name: main_net
  monitor_net:
    external: true
    name: monitor_net
