services:
  main_rust:
    build:
      context: ../backend
    image: main_rust:latest

  main_svelte:
    build:
      args:
        - PUBLIC_SWAP_BACKEND_PATH=${PUBLIC_SWAP_BACKEND_PATH}
        - PUBLIC_HOME_BACKEND_PATH=${PUBLIC_HOME_BACKEND_PATH}
        - PUBLIC_MAX_CHARS=${PUBLIC_MAX_CHARS}
        - PUBLIC_CODE_LENGTH=${PUBLIC_CODE_LENGTH}
        - PUBLIC_MEILI_PATH=${PUBLIC_MEILI_PATH}
        - PUBLIC_MEILI_URL=${PUBLIC_MEILI_URL}
        - PUBLIC_TEMP_SESSION_DURATION_SECS=${PUBLIC_TEMP_SESSION_DURATION_SECS}
        - PUBLIC_PAGE_SIZE=${PUBLIC_PAGE_SIZE}
        - PUBLIC_MIN_PASSWORD_LENGTH=${PUBLIC_MIN_PASSWORD_LENGTH}
        - PUBLIC_SVELTE_SWAP_ROOT=${PUBLIC_SVELTE_SWAP_ROOT}
        - PUBLIC_SVELTE_HOUSING_ROOT=${PUBLIC_SVELTE_HOUSING_ROOT}
        - PUBLIC_HOUSING_BACKEND_PATH=${PUBLIC_HOUSING_BACKEND_PATH}
        - PUBLIC_HOUSING_MAX_CHARS=${PUBLIC_HOUSING_MAX_CHARS}
        - PUBLIC_HOUSING_MIN_CHARS=${PUBLIC_HOUSING_MIN_CHARS}
      context: ../frontend
    image: main_svelte:latest

  main_caddy:
    build:
      context: ./caddy
    image: main_caddy:latest
